# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: kiara2
# "service" is the name of this project. This will also be added to your AWS resource names.
service: GestionCitasMedicas

provider:
  name: aws
  runtime: nodejs20.x
  iamRoleStatements:
    - Effect: Allow
      Action: 
        - dynamodb:*
      Resource: 
        - arn:aws:dynamodb:us-east-1:711387128226:table/CitaTable
  httpApi:
    cors:
      allowedOrigins:
        - http://localhost:3001
      allowedHeaders:
        - Content-Type
        - Authorization
      allowCredentials: true

functions:
  createCita:
    handler: src/createCita.createCita
    events:
      - httpApi:
          path: /citas
          method: post
  getCita:
    handler: src/getCita.getCita
    events:
      - httpApi:
          path: /citas
          method: get
  
  updateCita:
    handler: src/updateCita.updateCita
    events:
      - httpApi:
          path: /citas/{id}
          method: put

  deleteCita:
    handler: src/deleteCita.deleteCita
    events:
      - httpApi:
          path: /citas/{id}
          method: delete

resources:
  Resources:
    CitaTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: CitaTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
